# BANCO DE DADOS
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/barbearia_db}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD}

# HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

# EMAIL (Exemplo com Gmail/SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# SEGURANÇA E TOKENS
jwt.secret=${JWT_SECRET}
abacatepay.api.key=${ABACATEPAY_API_KEY}